#pragma once

#include "MenuClasses.h"

void fairly_often();
void at_a_paced_rate();
void once_in_a_while();
void refresh_mp3_player();
void loopusbHub();
void control_me();
void loop();
void initextmems();
void loadsynthdefaults();
void setupdefaultvalues();
void setuphubusb();
void unplugsynth();
void unplugfx();
void setupSD();
void setup();

void Volume_ctl(byte cc_value);
void SynthVolume_ctl(byte cc_value);
void SDPlayerVolume_ctl(byte cc_value);
void FlashVolume_ctl(byte cc_value);
void Wet1Volume_ctl(byte cc_value);
void Wet2Volume_ctl(byte cc_value);
void Wet3Volume_ctl(byte cc_value);
void DrySampler_ctl(byte cc_value);
void DrySynth_ctl(byte cc_value);
void DryAudioIn_ctl(byte cc_value);
void Slope1_ctl(byte cc_value);
void Slope2_ctl(byte cc_value);
void ArbitraryMaxF_ctl(byte cc_value);
void Filter303_ctl(byte cc_value);
void CutOffTweak_ctl(byte cc_value);
void ResoTweak_ctl(byte cc_value);
void set_Portamento_time_ctl(byte cc_value);
void set_Portamento_height_ctl(byte cc_value);
void FilterPreAmp_ctl(byte cc_value);
void ArpegioType_ctl(byte cc_value);
void ArpegioMode_ctl(byte cc_value);
void ArpegioNotesCount_ctl(byte cc_value);
void ArpegioStartOffset_ctl(byte cc_value);
void ArpegioGridC_ctl(byte cc_value);
void ArpegioGridS_ctl(byte cc_value);
void ArpegioLength_ctl(byte cc_value);
void TickFromStart_Trigger_ctl(byte cc_value);
void StartTicking_Trigger_ctl(byte cc_value);
void StopTicking_Trigger_ctl(byte cc_value);
void RecordCCPatern_Trigger_ctl(byte cc_value);
void RecordPattern_Trigger_ctl(byte cc_value);
void StopSong_Trigger_ctl(byte cc_value);
void PauseSong_Trigger_ctl(byte cc_value);
void PlaySong_Trigger_ctl(byte cc_value);
void SetChords_ctl(byte cc_value);
void SynthIndex_ctl(byte cc_value);
void SynthXFreq_ctl(byte cc_value);
void SynthXLevel_ctl(byte cc_value);
void PansLevels_ctl(byte cc_value);
void MetroDrumLevel_ctl(byte cc_value);
void SynthXModulationType_ctl(byte cc_value);
void SynthXtype_ctl(byte cc_value);
void SynthXOffset_ctl(byte cc_value);
void SynthXPhase_ctl(byte cc_value);
void AnalogTouch_Toggle_ctl(byte cc_value);
void LFOXLevel_ctl(byte cc_value);
void LFOXType_ctl(byte cc_value);
void LFOXFreq_ctl(byte cc_value);
void LFOXPhase_ctl(byte cc_value);
void LFOXOffset_ctl(byte cc_value);
void LFOXLSync_Toggle_ctl(byte cc_value);
void AdsrAtckDelay_ctl(byte cc_value);
void AdsrAttack_ctl(byte cc_value);
void AdsrHold_ctl(byte cc_value);
void AdsrDecay_ctl(byte cc_value);
void AdsrSustain_ctl(byte cc_value);
void AdsrRelease_ctl(byte cc_value);
void Filter303_Knob1_ctl(byte cc_value);
void Filter303_Knob2_ctl(byte cc_value);
void Filter303_Knob3_ctl(byte cc_value); 
void FXBusSelector_ctl(byte cc_value);
void ChorusVoices_ctl(byte cc_value);
void LFOonFilter_ctl(byte cc_value);
void BiQuadStage_ctl(byte cc_value);
void BiQuadFreq_ctl(byte cc_value);
void BiQuadSlope_ctl(byte cc_value);
void BiQuadGain_ctl(byte cc_value);
void BiQuadType_ctl(byte cc_value);
void GranularGrains_Knob1_ctl(byte cc_value);
void GranularSpeed_Knob2_ctl(byte cc_value);
void GranularShifting_Toggle_ctl(byte cc_value);
void GranularFreeze_Toggle_ctl(byte cc_value);
void ReverbSize_ctl(byte cc_value);
void BitCrusherSamples_ctl(byte cc_value);
void BitCrusherBits_ctl(byte cc_value);
void FFilter_Cutoff_Knob1_ctl(byte cc_value);
void FFilter_Reso_Knob2_ctl(byte cc_value);
void FFilter_Oct_Knob3_ctl(byte cc_value);
void FFilter_LowPass_Knob4_ctl(byte cc_value);
void FFilter_BandPass_Knob5_ctl(byte cc_value);
void FFilter_HighPass_Knob6_ctl(byte cc_value);
void FlangerOffset_Knob1_ctl(byte cc_value);
void FlangerDepth_Knob2_ctl(byte cc_value);
void FlangerDelay_Knob3_ctl(byte cc_value);
void DelayTimeSelection_Knob1_ctl(byte cc_value);
void DelayTimeMultiplier_Knob2_ctl(byte cc_value);
void DelayFeedback_Knob3_ctl(byte cc_value);
void AudioInVolume_ctl(byte cc_value);
void SetBPMs_ctl(byte cc_value);
void SaveToNewPattern_Trigger_ctl(byte cc_value);
void LoadFirstPattern_Trigger_ctl(byte cc_value);
void RecordAudio_Trigger_ctl(byte cc_value);
void PlayLoadedAudio_Trigger_ctl(byte cc_value);
void StopRecording_Trigger_ctl(byte cc_value);
void LoadFirstPreset_Toggle_ctl(byte cc_value);
void MergeSynthPatterns_Trigger_ctl(byte cc_value);
void FlashLineVolume_Knob1_ctl(byte cc_value);
void FlashLineVolume_Knob2_ctl(byte cc_value);
void FlashLineVolume_Knob3_ctl(byte cc_value);
void FlashLineVolume_Knob4_ctl(byte cc_value);
void FlashLineVolume_Knob5_ctl(byte cc_value);
void FlashLineVolume_Knob6_ctl(byte cc_value);
void FlashLineVolume_Knob7_ctl(byte cc_value);
void FlashLineVolume_Knob8_ctl(byte cc_value);
void FlashLineVolume_Knob9_ctl(byte cc_value);
void FlashLineVolume_Knob10_ctl(byte cc_value);
void FlashLineVolume_Knob11_ctl(byte cc_value);
void FlashLineVolume_Knob12_ctl(byte cc_value);
void FlashLineVolume_Knob13_ctl(byte cc_value);
void FlashLineVolume_Knob14_ctl(byte cc_value);
void FlashLineVolume_Knob15_ctl(byte cc_value);
void FlashLineVolume_Knob16_ctl(byte cc_value);
void USB_In_Volume_ctl(byte cc_value);
void toggle_stereo(byte cc_value);
void turn_off_stereo(byte cc_value);
void adjust_osc_timee_ctl(byte cc_val);
void adjust_osc_framerate_ctl(byte cc_val);
void adjust_osc_refresher_period_ctl(byte cc_val);
void adjust_rota_decrease_ctl(byte cc_val);
void rota_increase_ctl(byte cc_val);
void cancel_pushed_ctl(byte cc_val);
void validate_pushed_ctl(byte cc_val);
void adjust_waveEditor_pitch_ctl(byte cc_val);
void spectro_Toggle_ctl(byte unused_cc);
void eq_display_Toggle_ctl(byte cc_value);